### Model Configuration
model_name_or_path: /projects/b1222/userdata/jianshu/chengxuan/saved/models/Qwen2.5-VL-3B-Instruct  # Using 3B model
image_max_pixels: 1003520  # 1280*28*28 = ~1M pixels (matches training data config)
video_max_pixels: 16384   # Maximum pixels for video input (if needed)
trust_remote_code: true

### Training Method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_alpha: 16
lora_target: all
lora_dropout: 0.05

### Dataset Configuration
# Using frm_cold_all dataset (18,580 samples: 7,572 text + 11,008 visual)
dataset: frm_cold_all
template: qwen2_vl
cutoff_len: 30000  # Increased to handle longer sequences with images
max_samples: null # Use all 18,580 samples
overwrite_cache: true
preprocessing_num_workers: 48
dataloader_num_workers: 16
media_dir: /projects/p32958/chengxuan/new_extracted_images/images # Directory containing images

### Output Configuration
output_dir: /projects/p32958/Results/sft_model/qwen25vl_3b  # Updated for 3B model and FRM dataset
logging_steps: 1
save_steps: 20
save_total_limit: 3  # Keep only the last 3 checkpoints
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # Options: none, wandb, tensorboard, swanlab, mlflow

### Training Hyperparameters
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
warmup_steps: 0
weight_decay: 0.0
optim: adamw_torch
bf16: true
fp16: false
max_grad_norm: 1.0
ddp_timeout: 180000000
resume_from_checkpoint: null  # Set to checkpoint path if resuming

### Evaluation (Optional)
val_size: 0.0  # Set to 0.1 for 10% validation split
per_device_eval_batch_size: 1
eval_strategy: "no"  # Options: no, steps, epoch
eval_steps: 500
# do_eval: false

### Logging and Checkpointing
logging_first_step: true
save_on_each_node: false
save_safetensors: true

### Other Settings
seed: 42
